### ISSUE TITLE
Make 08-sharing-images.md work through VS Code container

### ISSUE THREAD

**Issue by MichaelDepner** [eficode-academy/code-server#4]
If the exercises are being run in a `praqma/vscode` container, it is not currently possible to `docker login`, ~since it saves the credentials within the container, and the docker commands are being run from the host.~

One way of solving this is to install a different authentication method inside `praqma/vscode`:
`apt install gnupg2 pass`
(https://stackoverflow.com/questions/50151833/cannot-login-to-docker-account)

We could add it to the exercise as a hint:
>Hint: If authentication fails, you can run `apt install gnupg2 pass` and try again

Maybe a better solution is to update `praqma/vscode` to include these packages. However, I have no idea where this docker image actually comes from. For now I am documenting the issue here. Will explore further...

~edit: Alternatively, figure out whether an extra bind-mount to the credentials file location will make the problem go away.~

**Comment by MichaelDepner** [comment]
Moved this to https://github.com/praqma-training/code-server, since it isn't really a problem with the katas.

**Comment by hoeghh** [comment]
I just tried a docker login in the new vscode and it seems to work fine.
Could you try it again?
![vscode-docker-login](https://user-images.githubusercontent.com/11328908/95322742-41195900-089d-11eb-9d6f-5b737a201f79.png)
